// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfi7gp75xldKvdzelgjsQPEtBr4O-97Y',
    appId: '1:694724285647:android:a732c8526ead7d244c53ba',
    messagingSenderId: '694724285647',
    projectId: 'fooddeliveryapp-ddc73',
    storageBucket: 'fooddeliveryapp-ddc73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv6D4X0-fXMChve63b3Ca2WX-zd5mYP90',
    appId: '1:694724285647:ios:c5a52a5b73dc99694c53ba',
    messagingSenderId: '694724285647',
    projectId: 'fooddeliveryapp-ddc73',
    storageBucket: 'fooddeliveryapp-ddc73.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv6D4X0-fXMChve63b3Ca2WX-zd5mYP90',
    appId: '1:694724285647:ios:c5a52a5b73dc99694c53ba',
    messagingSenderId: '694724285647',
    projectId: 'fooddeliveryapp-ddc73',
    storageBucket: 'fooddeliveryapp-ddc73.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
